//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazineOrdersClients
    {
        public MagazineOrdersClients()
        {
            this.WorkOfOrders = new HashSet<WorkOfOrders>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime Дата_приема { get; set; }
        public System.DateTime Дата_сдачи { get; set; }
        public int idClient { get; set; }
        public int idManagers { get; set; }
        public int idWorker { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<WorkOfOrders> WorkOfOrders { get; set; }
    }
}
