//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public Managers()
        {
            this.MagazineOrdersClients = new HashSet<MagazineOrdersClients>();
        }
    
        public int ManagerID { get; set; }
        public string ФИО { get; set; }
        public string Номер_телефона { get; set; }
    
        public virtual ICollection<MagazineOrdersClients> MagazineOrdersClients { get; set; }
    }
}
